### ISSUE TITLE
Multiple folders autocomplete problem.

### ISSUE THREAD

**Issue by milkpuff** [sublimelsp/LSP-pyright#190]
If 2 or more folders added to project, autocomplete project seems to fail.
![屏幕截图 2022-09-18 143127](https://user-images.githubusercontent.com/21542697/190889277-0a681feb-ebb6-403d-837b-878ad6cabe2e.png)
(test.py is outside of the project.)

If only one folder added to project, autocomplete runs perfect.

![屏幕截图 2022-09-18 143213](https://user-images.githubusercontent.com/21542697/190889358-863c0bdb-af9b-4fc7-a5ed-66b33a597a32.png)
![屏幕截图 2022-09-18 143255](https://user-images.githubusercontent.com/21542697/190889359-a6d9068b-60b5-4635-9df6-5a57ad1c056a.png)

setting:
```json
{
	"settings": {
		"python.pythonPath": "G:/miniconda3/envs/py310/python.exe",
	}
}
```

**Comment by jfcherng** [comment]
Only the first folder will be considered as the project folder iirc.

**Comment by rchl** [comment]
It's up to the server rather. If it supports multiple workspace folders than it should work regardless. And i think pyright does support multiple workspace folders. 
Have to be analysed more to see where the issue is exactly.

**Comment by jfcherng** [comment]
The payload to the server seems good.

```py
'rootUri': 'file:///E:/Repo/ST-Fanhuaji', 
'workspaceFolders': [
{'name': 'ST-Fanhuaji', 'uri': 'file:///E:/Repo/ST-Fanhuaji'}, 
{'name': 'ST-Emoji', 'uri': 'file:///E:/Repo/ST-Emoji'}], 
'rootPath': 'E:\\Repo\\ST-Fanhuaji'}
```

**Comment by rchl** [comment]
I've missed the fact that the `test.py` is outside of any of those projects. In that case I can indeed see that the behavior is different depending on if there is one folder or more but LSP doesn't seem to be treating those cases differently otherwise so I think this is pyright's bug or feature.

I suggest reporting it at https://github.com/microsoft/pyright and you'll get clarification, if nothing else.
