### ISSUE TITLE
Pyright tooltip syntax can't be loaded

### ISSUE THREAD

**Issue by AmjadHD** [sublimelsp/LSP-pyright#264]
![image](https://cdn.discordapp.com/attachments/645268178397560865/1140066396265517107/image.png)
![image](https://cdn.discordapp.com/attachments/645268178397560865/1140065827522084925/image.png)
ST 4152
LSP 1.24.0
LSP-Pyright 1.1.157

**Comment by jfcherng** [comment]
Likely you have a custom Python syntax?

**Comment by jfcherng** [comment]
Likely fixed by https://github.com/sublimelsp/LSP-pyright/commit/9cd3f49c7508bf6cb187f7bb29b136f78310c381

We should move Packages/LSP-pyright/syntaxes/Python.sublime-syntax from this Package and just use the default Python syntax, which also uses version:2 now. But what's the decent migration method on our side?

**Comment by AmjadHD** [comment]
It's fixed. Thanks.
