### ISSUE TITLE
[ST4] Adjust extraPaths in the `on_settings_changed` callback

### ISSUE THREAD

**Issue by rwols** [sublimelsp/LSP-pyright#30]
The extra paths are adjusted when the plugin is first loaded by LSP, but this prevents changing the path by the user at a later date (in their Packages/User/LSP-pyright.sublime-settings). We should instead adjust the path in ~~AbstractPlugin.on_workspace_configuration~~ ~~AbstractPlugin. on_pre_workspace_did_change_configuration~~ AbstractPlugin.on_settings_changed. May depend on https://github.com/sublimelsp/lsp_utils/pull/37

**Comment by rchl** [comment]
Did you mean `on_pre_workspace_configuration` (now renamed to `on_pre_workspace_did_change_configuration`)?

**Comment by rchl** [comment]
Actually, we would need to override both `on_workspace_did_change_configuration` and `on_workspace_configuration` since those are copies of the configuration object so altering configuration from the former won't persist for the latter.

I don't like where it's going...

**Comment by rchl** [comment]
I'm thinking it might be necessary to have an API like `on_settings_changed` that would be triggered when changes are actually changed (and on init also). That would be the cleanest and efficient way to do it instead of having to alter the settings each time the server asks for them using `workspace/configuration` (and also when we send workspace/didChangeConfiguration`.

**Comment by rwols** [comment]
But workspace/configuration has the complication that it has a scopeUri, which can be a folder, or a view (or even some strange URI as I'm learning from jdtls).

**Comment by rchl** [comment]
Does that affect this case though?

If it requests a section then that section is from the current settings object.
If it requests something from outside of the settings object then there will have to be a custom handling for that anyway.

**Comment by jfcherng** [comment]
I am duplicating codes in 3 different places because each of them has tiny differences.

- `def on_settings_read(cls, settings: sublime.Settings) -> bool`: for ST 3
- `def on_workspace_configuration(self, params: Dict, configuration: Dict[str, Any]) -> None:`:
  The `configuration` I get is a nested `dict` which causes a major pain if I don't use my own `dotted_set()` utility function. I thought of converting `configuration` into `DottedDict` and use its utils but soon I found the `DottedDict` is just a copy so it won't work, `configuration` is still there.
- `def on_workspace_did_change_configuration(self, settings: DottedDict) -> None:`:
  This is less painful since `DottedDict` has some useful utils. But still, duplicated codes.

**Comment by jfcherng** [comment]
Another issue, newly added setting in `on_workspace_did_change_configuration()` won't be (variable) expanded again. `on_workspace_configuration()` is fine.

**Comment by rwols** [comment]
So we want to do variable expansion after the plugin did something to it, not before?

**Comment by jfcherng** [comment]
> So we want to do variable expansion after the plugin did something to it, not before?

Ah! I guess the current state is fine. I thought it's an issue because I bundled my own ST stubs with my custom LSP-* plugin and variables defined in `additional_variables()` is not expanded after `on_workspace_did_change_configuration()`. 

```py
    @classmethod
    def inject_extra_paths_st(cls, settings: Dottedable, key_extraPaths: str) -> None:
        extraPaths = dotted_get(settings, key_extraPaths, [])  # type: List[str]

        extraPaths.append("$server_directory_path/_resources/typings")  # <------------------------
        extraPaths.extend(cls.find_package_dependency_dirs())
        extraPaths.append(sublime.installed_packages_path())

        dotted_set(settings, key_extraPaths, list(unique(extraPaths, stable=True)))
```

But that's probably okay since I can manually expanded it.

**Comment by rchl** [comment]
@jfcherng if you have to make so much code (ref https://github.com/sublimelsp/LSP-pyright/issues/30#issuecomment-727715552) to make it work then there is likely a problem with the API. I wouldn't recommend going forward with that.

**Comment by jfcherng** [comment]
yeah I think something will be changed so I didn't make a PR at this moment.

**Comment by rchl** [comment]
I'm proposing something to solve this at https://github.com/sublimelsp/LSP/pull/1482

For ST3, something would have to be added to the ST3 branch probably.
