### ISSUE TITLE
feature request: add support for format file via autopep8/yapf

### ISSUE THREAD

**Issue by krisfans** [sublimelsp/LSP-pyright#65]

**Comment by jfcherng** [comment]
Are them supported by pyright itself?

**Comment by krisfans** [comment]
Probably not, but I think it would be better if this plugin can support it. see microsoft/pyright#213

**Comment by rwols** [comment]
It’s an explicit non-goal of pyright to enforce any kind of style. I’m sure there are already yapf or autopep8 formatter plugins on package control.

**Comment by rchl** [comment]
Since `LSP-pylsp` supports formatters, I'd rather look into running them simultaneously and using `LSP-pylsp` for formatting only. With ability to disable capabilities it would hopefully be possible but I haven't tried.

Please create an issue in LSP-pylsp repo if you care. If we figure out the exact settings then we can add that to documentation.
